package unitControlModule.stateFactories.actions.executableActions;

import bwapiMath.Point;

/**
 * RetreatPositionValidator.java --- Interface for validating the Positions
 * generated by the {@link RetreatPositionCluster}. These Positions must be
 * verified by a {@link RetreatPositionValidator} for them to be enabled for
 * Unit assignment.
 * 
 * @author P H - 19.08.2017
 *
 */
public interface RetreatPositionValidator {

	// TODO: UML ADD PARAM
	/**
	 * Function for validating a Position generated by the
	 * {@link RetreatPositionCluster}.
	 * 
	 * @param position
	 *            the Position that is going to be validated.
	 * @param isLeaderPosition
	 *            flag indicating wheter the Position being checked is the
	 *            leader's position or not.
	 * @return true if the Position is a valid one, false if it should be marked
	 *         as invalid.
	 */
	public boolean validatePosition(Point position, boolean isLeaderPosition);
}
